### ISSUE TITLE
calendar help

### ISSUE THREAD

**Issue by svargas93** [jangellx/MagicMirror#1]
where do i input my personal calendar? i tried on calendar.php

**Comment by jangellx** [comment]
I don't actually use the calendar feature from Michael's code.  I didn't remove any of the code, though, so it should work as per Michael's original calendar instructions (meaning, editing calendar.php like you were doing).

I just gave it a try here by uncommenting the first $url variable in calendar.php, and it seemed to work fine.

**Comment by svargas93** [comment]
Awesome thanks! sorry to keep bothering you..

 if the event is tomorrow it will show as 

birthday event tomorrow is

would it be hard to to edit the "is" out

**Comment by jangellx** [comment]
I see; the calendar code is using moment.js.  I'm using it for the holidays as well, and I used different formatting by overriding the moment.locale() at the top of the file.

I've changed the code to set the custom format just before updating the holiday text, and clearing the format just before updating the calendar text.  That should fix the problem for you.

**Comment by svargas93** [comment]
okay so i updated like you stated and the weather and my personal calendar are gone would this have anything to do with it?

**Comment by jangellx** [comment]
It shouldn't; this code made no changes to the weather.  I have it running on my Windows machine (I use that for developing this, then push it to the Raspberry Pi) and everything seems fine.  The calendar was working when I tried it, too.

**Comment by svargas93** [comment]
hm okay ill keep messing with it

**Comment by svargas93** [comment]
hey thanks a lot for your time! I got everything done and it looks great!
